/**
 * Ambient module declaration for the Emscripten-generated engine.js.
 *
 * This file is generated by the WASM build (emcmake cmake / cmake --build).
 * The declaration exists so TypeScript can resolve the dynamic import
 * before the WASM build has run.
 */
declare module "*/wasm/engine.js" {
  import type { EngineModule } from "./wasm";
  const createEngineModule: () => Promise<EngineModule>;
  export default createEngineModule;
}
